### ISSUE TITLE
window not define

### ISSUE THREAD

**Issue by Ibnyahyah** [PiNetwork-js/sdk#10]
ReferenceError: window is not defined
    at Object.<anonymous> (C:\Users\User\Documents\Workspace\projects\_pi\client\node_modules\@pinetwork-js\sdk\build\handlers\MessageHandler.js:103:1)

**Comment by B-Derouet** [comment]
Hi, can you provide me your environment and how do you use the SDK? It seems that you're not using for a web application ("window" is defined in browser environment).

**Comment by Ibnyahyah** [comment]
I was trying to use it in a nextjs app. But after I add an if check on it , its get rid of the bug.
