### ISSUE TITLE
New SDK

### ISSUE THREAD

**Issue by B-Derouet** [PiNetwork-js/sdk#9]
Core Team published a new version of the SDK recently :
- [x] Update Axios dependency
- [x] Update SDK message timeout from 60000ms to 120000ms
- [x] Add `nativeFeaturesList()` method in PiClient class (new message type `@pi:app:sdk:check_native_features`)
- [x] Add `retryableCallback()` method in PaymentHandler class (new message type `@pi:app:sdk:decide_callback_retrial`)

**Comment by yogi211517** [comment]
are you willing to make me paymen pi on my online shop website, if willing I am ready to pay you
